name=subways_3000_series
title=3000 Series (Subways)
description=3000 Series Subway Train
depends=advtrains, advtrains_train_track, subways
optional_depends=advtrains_attachment_offset_patch, advtrains_livery_designer
