name=subways_lrv_p3010
title=LRV P3010 (Subways)
description=P3010 Light Rail Vehicle
depends=advtrains, advtrains_train_track, subways
optional_depends=advtrains_attachment_offset_patch, advtrains_livery_designer
